export const ADD_INGEDRIENT = "ADD_INGEDRIENT";
export const REMOVE_INGEDRIENT = "REMOVE_INGEDRIENT";
/**
 * action Type
 */
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
